// Mock data for development
export const MOCK_TODOS = [
  {
    id: 1,
    user_id: 5,
    title: 'Complete project proposal',
    description: 'Prepare and review the Q3 project proposal for the marketing team. Include budget analysis and timeline.',
    status: 'completed' as const,
    created_at: '2026-05-25T10:30:00Z',
    updated_at: '2026-05-26T14:20:00Z',
  },
  {
    id: 2,
    user_id: 5,
    title: 'Review API documentation',
    description: 'Go through the updated API docs and provide feedback on clarity and completeness.',
    status: 'pending' as const,
    created_at: '2026-05-26T09:15:00Z',
    updated_at: '2026-05-26T09:15:00Z',
  },
  {
    id: 3,
    user_id: 5,
    title: 'Schedule team meeting',
    description: 'Set up a meeting with the engineering team to discuss the roadmap for next quarter.',
    status: 'pending' as const,
    created_at: '2026-05-27T11:45:00Z',
    updated_at: '2026-05-27T11:45:00Z',
  },
  {
    id: 4,
    user_id: 5,
    title: 'Update user authentication flow',
    description: 'Implement two-factor authentication and update the login process for better security.',
    status: 'pending' as const,
    created_at: '2026-05-27T14:00:00Z',
    updated_at: '2026-05-27T14:00:00Z',
  },
  {
    id: 5,
    user_id: 5,
    title: 'Fix bug in dashboard',
    description: 'The statistics cards are showing incorrect calculations. Need to debug and fix the logic.',
    status: 'pending' as const,
    created_at: '2026-05-28T08:30:00Z',
    updated_at: '2026-05-28T08:30:00Z',
  },
  {
    id: 6,
    user_id: 5,
    title: 'Prepare quarterly report',
    description: 'Compile performance metrics and prepare the quarterly business report.',
    status: 'completed' as const,
    created_at: '2026-05-20T10:00:00Z',
    updated_at: '2026-05-23T16:45:00Z',
  },
];
